name: PlaytimeUtils
version: '${version}'
author: p0t4t0sandwich
main: ca.sperrer.p0t4t0sandwich.playtimeutils.bukkit.BukkitMain
folia-supported: true
commands:
  playtime:
    description: Get the playtime of a player
    usage: /playtime